### ISSUE TITLE
Handling multiple input files

### ISSUE THREAD

**Issue by hoschi-it** [JohannesFKnauf/parti-time#6]
Hi @JohannesFKnauf 

I absolutely love this project of yours, thanks for making it publicly available!
As I personally like to split things into multiple files before becoming too large, I am trying to make it possible to generate timesheets using multiple input files at once.

I was wondering whether there is a simple way to implement this here, though it works with a bash wrapper and I unfortunately do not have any prior knowledge in Clojore nor any other LISP-like language.

Just a suggestion, don't bother to answer if you're too busy.

---

# Suggestion 1
Detect the format (yaml vs. tl) using the first line of the file.
This would allow the use of 
```
parti-time timesheet <( cat 2024-*.tl )
```

# Suggestion 2
Allow the user to pass multiple files
```bash
parti-time timesheet 2023-12-*.tl 2024-01-03.tl 2024-01-04.tl 
```

# External solution
The current workflow is

- concatenating those *.tl files together, putting an empty line in between
- writing this to a temporary file
- providing the path to the temporary file to parti-time
- removing the temporary file

Thanks a lot
hoschi

**Comment by JohannesFKnauf** [comment]
Hi Hoschi, thanks for your kind words. I am flattered!

In fact, I am facing the same issue as you. Let me share my current plans in a separate post. I'll be happy to hear your opinion. I assume I will be able to summarize it tonight or tomorrow.

**Comment by JohannesFKnauf** [comment]
Right now, `parti-time` works with individual files. Originally I had the idea, that it should work just like a UNIX tool, e.g. also allow for feeding stdin/stdout, pipelining, etc.

As it turned out during development and regular usage, `parti-time` has a very different nature. It's rather repository-oriented. It stores long-term time-tracking data.

Most of the time I am only interested in the current month, but sometimes in completely different timeframes -- longer timeframes like a full quarter as well as shorter timeframes like a single day or the current week.

As a consequence, I imagine the UX of `parti-time` to change in the next major version. The detailed repository storage format would be hidden from the user. It's not necessarily 1 or more `tl` files. (It may even become pluggable with support for different storage backends, but that's not the important point.)

### `tl` evolves from storage format to UX feature
But then again, how will a user interact with `parti-time`? What becomes of its powerful `tl` DSL?

The `tl` file format will be decoupled from the storage format. When it comes to editing, I imagine a user specifying a timeframe in their command, e.g. (pseudo-syntax, subject to change)

```
# 2 ways to edit Q4 in 2023
pt edit 2023-10-01 -- 2023-12-31
pt edit 2023/Q4

# 2 ways to edit January 2024
pt edit 2023/01
pt edit 2023-01-01 -- 2023-01-31

# shortcuts for typical timeframes
pt edit this day
pt edit next day
pt edit this month
pt edit this week
```

`parti-time` will open a temporary file in the default editor (e.g. using environment variable `VISUAL`) and use it's content after closing. This is similar to other Unix tools, for example `vipe` from [`moreutils`](https://joeyh.name/code/moreutils/) or bash's readline edit command (`C-x C-e` with emacs keybindings).

What do you think?

### Regarding the suggestions
Otherwise, I think both of your suggestions don't contradict, but rather supplement each other. I like them. Also, detecting the format by the first relevant tokens in the token stream should be feasible (the first line won't be enough, though).

**Comment by hoschi-it** [comment]
While I personally will stick with the `tl` format, because this will allow me to write my own simple set of tools for statistics and will never end in a tool lock-in, having an `edit` subcommand for opening an editor with the respective timeframes data and handling the storage back-end for the user seems like a great thing to me.

This is a big change though, that might require migrating current `*.tl` files to a location and directory structure parti-time knows about.

**Comment by JohannesFKnauf** [comment]
Thanks for your feedback and for raising the points about tool flexibility and lock-in. I'll take them into consideration, when I design those future features.

I've been pondering over your original request and would like to ask you, what you would think, if I just ditched auto-detection. That would mean that there is an explicit option -- e.g. `--format` or `--input-format` -- to specify/override the format of the input(s), with `tl` as default format.

**Comment by hoschi-it** [comment]
>I [...] would like to ask you, what you would think, if I just ditched auto-detection.
Sure, auto-detection might not be that important of a feature and it's not easy to implement it cleanly.

> That would mean that there is an explicit option -- e.g. `--format` or `--input-format` -- to specify/override the format of the input(s), with `tl` as default format.


This sounds like a sensible way to approach the issue in my opinion.

Thanks for sharing your plans by the way, I appreciate that.

**Comment by JohannesFKnauf** [comment]
I had a chance to have a look into the topic tonight. I prepared PR #9 that would:
* allow filenames without extensions (incl. the pseudofilenames created by bash process substituion (`<(...)`)
* allow to explicitly read from stdin / write to stdout by passing the special filename `-` (as many unix commands do)

This allows to use process substitution and pipelining in the shell. Ideally that would mean
```
# Beware! Those are dummy examples, that don't work!
pt projects <(cat *.tl)
cat *.tl | pt projects -
```
In fact, right now catting multiple valid `tl` timelines does not result in a valid `tl` file, since the mandatory separating newlines will be missing. Here is an (admittedly ugly) workaround:
```
# This looks ugly, but it works.
awk 'FNR==1 && NR > 1 {print ""} {print}' *.tl | pt projects -
```
Short explanation:
* `FNR ==1` means execute the `{print ""}` (insert newline) only for the first row of each input file
* `NR > 1` means don't execute the `{print ""}` (insert newline) for the first input file (you'd have a bogus leading newline otherwise)
* `{print}` means, that we otherwise always echo every line in each file without modification

If one needs the command more often, I'd recommend creating a little shell alias, shell function or wrapper shell script.

I chose this design instead of implementing the explicit options we discussed above, to be able to provide this feature more quickly and avoid getting blocked in the preparation of the next major release (which includes cleaning the CLI usage).

@hoschi-it Would that help you for now?

**Comment by hoschi-it** [comment]
Sure things, this will make things much easier.

I also think that for adding newlines in between .tl-files using a wrapper that inserts those should be sufficient, though not beautiful.

Thanks a lot for your effort @JohannesFKnauf , I really appreciate that!

**Comment by JohannesFKnauf** [comment]
@hoschi-it You might be interested to learn, that [the latest parti-time release 1.2.0](https://github.com/JohannesFKnauf/parti-time/releases/tag/v1.2.0) features a new sub-command `cat`, that enables you to concatenate multiple timeline files to a single tl timeline. Just be careful with the order, since there will be no cross-validation of the resulting output timeline! (At least not yet.)

Now you get away with e.g.
```
pt cat TimeTracker.2024-0* | pt projects -
```
or (equivalent)
```
pt projects <(pt cat TimeTracker.2024-0*)
```
instead of the ugly alias workaround described above.

**Comment by hoschi-it** [comment]
What a great news! Thanks a lot for all your work on this matter @JohannesFKnauf 

This will bring huge benefit to me personally. For a matter of fact, when prefixing the filenames with their corresponding start date (which I do), bash will take care of the correct order automatically.
